# This is an axolotl config that allowed creation of a model knowledgeable about Verus.
# Replace the dataset paths under `datasets:` with your own
# If you want a reference point of what kind of data was fed into this model, check out Verustoolkit https://github.com/e-p-armstrong/verustoolkit.git

# Rent a GPU with a compute provider like Vast.ai or Runpod
# (Make sure it is using the axolotl docker image --- winglian/axolotl:main-latest)
# Copy this file over to the rented instance, in the /workspace/axolotl directory
# If running on a single-GPU setup, you must run:
# conda install -c conda-forge mpi4py mpich
# Then run this command from the /workspace/axolotl directory:
# accelerate launch --use_deepspeed -m axolotl.cli.train axolotl_config_verus_llama3_Jun_9_2024.yaml

# If using GaLore, do not use deepspeed

# (to copy files over to a rented GPU instance, you'll have to use SSH to Secure CoPy files over from your machine to the rented one. This is what such a command might look like, adapt it to your needs)
# scp -P 40001 -r ./ root@173.231.62.170:/workspace/axolotl/

base_model: Qwen/Qwen1.5-32B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: json
    data_files: pretraining_medium.json
    ds_type: json
    type: completion
  - path: json
    data_files: simplified_data_rag_MEDIUM.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_MEDIUM.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_MEDIUM_NEGATIVE.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_rag_OPENENDED_MEDIUM.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_OPENENDED_MEDIUM.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: orca_split_1.json
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: synthetic_data_hallucination_defence_current.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: orca_split_2.json
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: pretraining_wiki.json
    ds_type: json
    type: completion
  - path: json
    data_files: simplified_data_rag_WIKI.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_WIKI.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_WIKI_NEGATIVE.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_rag_OPENENDED_WIKI.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_OPENENDED_WIKI.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: cot_alpaca_split_1.json
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: unnatural_split_2.json
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: synthetic_data_hallucination_defence_absurd.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: pretraining_api.json
    ds_type: json
    type: completion
  - path: json
    data_files: simplified_data_rag_API.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_API.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_API_NEGATIVE.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_rag_OPENENDED_API.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_OPENENDED_API.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: cot_alpaca_split_2.json
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: unnatural_split_2.json
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: pretraining_docs.json
    ds_type: json
    type: completion
  - path: json
    data_files: simplified_data_rag_DOCS.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_DOCS.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_DOCS_NEGATIVE.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_rag_OPENENDED_DOCS.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_OPENENDED_DOCS.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json ## INSERTION POINT
    data_files: evol_split_1.json
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json 
    data_files: unnatural_split_1.json
    ds_type: json
    type: sharegpt
    conversation: chatml   #
  - path: json
    data_files: synthetic_data_hallucination_defence_community.jsonl 
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: pretraining_vision.json
    ds_type: json
    type: completion
  - path: json
    data_files: simplified_data_rag_VISION.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_VISION.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_rag_OPENENDED_VISION.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml # synthetic_data_hallucination_defence_combined_reminder.jsonl
  - path: json
    data_files: synthetic_data_hallucination_defence_combined_reminder.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml
  - path: json
    data_files: simplified_data_no_rag_OPENENDED_VISION.jsonl
    ds_type: json
    type: sharegpt
    conversation: chatml

dataset_prepared_path: last_run_prepared
output_dir: ./verus-out-no-new-tokens

sequence_len: 4500
sample_packing: true
pad_to_sequence_len: true

wandb_project: military-llama-revision
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 6
micro_batch_size: 1
num_epochs: 6
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-4
noisy_embedding_alpha: 0 # no noisy embedding to ensure maximal memorization 

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: unsloth
early_stopping_patience:
resume_from_checkpoint: 
logging_steps: 1
xformers_attention:
flash_attention: true

chat_template: chatml

warmup_steps: 100
auto_resume_from_checkpoints: false
eval_steps: 10
saves_per_epoch: 1
eval_sample_packing: false
save_total_limit: 4
debug:
deepspeed: deepspeed_configs/zero2.json
special_tokens:
  pad_token: "<|end_of_text|>"